name: PhoenixAnimations
version: '1.1'
main: com.bocktom.phoenixAnimations.PhoenixAnimations
api-version: '1.21'
commands:
  animation:
    description: Play a custom animation
    usage: /animation or /animation <name>
    permission: phoenixanimations.animation
permissions:
  phoenixanimations.animation:
    description: Allows the player to use the /animation command
    default: true
  phoenixanimations.purchase:
    description: Allows the player to purchase animations
    default: op
depends:
  - BetterModel
  - LuckPerms